apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: A-Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches:
      - "**"

jobs:
  build:
    steps:
      - name: Run A-Build
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "A-Built"
