apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: A-Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Run A-Deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "A-Deployed"
