apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-90

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Run Sleep-90
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 90
          echo "Sleep-90 is done"
