apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-20

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Run Sleep-20
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 20
          echo "Sleep-20 is done"
