apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-00
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Run Sleep-00
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Sleep-00 is done"
