apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-50

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Run Sleep-50
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 50
          echo "Sleep-50 is done"
