apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-10

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Run Sleep-10
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 10
          echo "Sleep-10 is done"
