apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-80

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Run Sleep-80
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 80
          echo "Sleep-80 is done"
