apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-30
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Run Sleep-30
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 30
          echo "Sleep-30 is done"
