apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sleep-40

on:
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: Run Sleep-40
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 40
          echo "Sleep-40 is done"
